ci:
  autofix_commit_msg: "pre-commit autofix run"
  autoupdate_commit_msg: "pre-commit autoupdate hooks"

repos:
  - repo: local
    hooks:
      - id: spectral-linter
        name: spectral-linter
        language: node
        entry: npx spectral lint ./reference/**/*.yaml
        files: ^reference/
        types: [yaml]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
