repos:
  - repo: https://github.com/python-openapi/openapi-spec-validator
    rev: 0.5.6
    hooks:
      - id: openapi-spec-validator
        files: reference\/.+\.yaml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
