openapi: 3.1.0

x-stoplight:
  id: f3thjnkfyv60k

info:
  title: Agency
  version: "2.0"
  summary: The Agency API endpoints are intended to be implemented by regulatory agencies and consumed by mobility providers.
  contact:
    url: https://github.com/openmobilityfoundation/mobility-data-specification
    name: Open Mobility Foundation
    email: info@openmobilityfoundation.org
  license:
    name: Creative Commons Attribution 4.0 International Public License
    url: https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/LICENSE
  description: |-
    The Agency API endpoints are intended to be implemented by regulatory agencies and consumed by mobility providers.

    Data is **pushed** to agencies by providers. Providers query the Agency API when events (such as a trip start or vehicle
    status change) occur in their systems.

    This specification contains a collection of RESTful APIs used to specify the digital relationship between _mobility as a service_
    providers and the agencies that regulate them.

components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      description: |-
        All MDS Agency endpoints require authentication.

        JSON Web Token ([JWT](https://jwt.io/introduction/)) is RECOMMENDED as the token format.

        When making requests, the endpoints expect `provider_id` to be part of the claims the JWT. The token issuance,
        expiration and revocation policies are at the discretion of the agency.

paths:
  /vehicles:
    post:
      operationId: vehicles-register
      description: Register vehicles for use in the Agency's jurisdiction.
      summary: Register new vehicles.
      responses:
        "201":
          description: Vehicles registered.
          content:
            application/vnd.mds+json: {}
        "401":
          description: "Unauthorized: Invalid, expired, or insufficient scope of token."
        "404":
          description: Vehicles not found.
        "406":
          description: MDS version in Accept header is unsupported or invalid.
    get:
      operationId: vehicles-list
      description: Get a list of vehicles in a Provider's registered fleet, with properties that do not change often.
      summary: Get registered vehicle information.
      responses:
        "200":
          description: Vehicles found.
          content:
            application/vnd.mds+json: {}
        "401":
          description: "Unauthorized: Invalid, expired, or insufficient scope of token."
        "404":
          description: Vehicles not found.
        "406":
          description: MDS version in Accept header is unsupported or invalid.
