openapi: 3.1.0

x-stoplight:
  id: ebvdax2uwqdyo

info:
  title: MDS - Mobility Data Specification
  version: "2.0"
  summary: MDS is a data standard to enable right-of-way regulation and two-way communication between mobility companies and local governments.
  description: The Mobility Data Specification (MDS), a project of the Open Mobility Foundation (OMF), is a data standard to enable right-of-way regulation and two-way communication between mobility companies and local governments.
  contact:
    url: https://github.com/openmobilityfoundation/mobility-data-specification
    name: Open Mobility Foundation
    email: info@openmobilityfoundation.org
  license:
    name: Creative Commons Attribution 4.0 International Public License
    url: https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/LICENSE

tags:
  - name: provider
  - name: agency
  - name: policy
  - name: geography
  - name: jurisdiction
  - name: metrics

components:
  oauth:
    type: oauth2
    flows:
      clientCredentials:
        tokenUrl: ""
        refreshUrl: ""
        scopes:
          example: If an MDS endpoint producer implements this auth scheme, it MAY choose to specify token scopes that define access parameters like allowable time ranges. These guidelines SHOULD be encoded into the returned token in a parsable way.
    description: |-
      OAuth 2.0's `client_credentials` grant type (outlined in [RFC6749](https://tools.ietf.org/html/rfc6749#section-4.4)) is RECOMMENDED as the authentication and authorization scheme.

      OAuth 2.0 is an industry standard authorization framework with a variety of existing tooling. The `client_credentials` grant type facilitates generation of tokens that can be used for access by agencies and distributed to data partners.
