openapi: 3.1.0

x-stoplight:
  id: q6wapocoxbhs1

info:
  title: Policy
  version: "2.0"
  summary: The Policy API endpoints are intended to be implemented by regulatory agencies and consumed by mobility providers.
  contact:
    url: https://github.com/openmobilityfoundation/mobility-data-specification
    name: Open Mobility Foundation
    email: info@openmobilityfoundation.org
  license:
    name: Creative Commons Attribution 4.0 International Public License
    url: https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/LICENSE
  description: |-
    The Policy API endpoints are intended to be implemented by regulatory agencies and consumed by mobility providers.
    Providers query the Policy API to get information about local rules that may affect the operation of their mobility service
    or which may be used to determine compliance.

    This specification describes the digital relationship between _mobility as a service_ providers and the agencies that regulate
    them. The Policy API communicates municipal policies (such as as vehicle deployment caps and speed limits) in a clear,
    consistent manner.

    All Policy endpoints should be made public. Authorization is not required.

paths:
  /policies:
    parameters:
      - name: start_date
        schema:
          $ref: ../models/data-types/timestamp.yaml
        in: query
        required: false
        description: Beginning date of the queried time range; the default value is the request time.
      - name: end_date
        schema:
          $ref: ../models/data-types/timestamp.yaml
        in: query
        required: false
        description: Ending date of the queried time range; the default value is null, which captures all policies that are effective in the future.
    get:
      operationId: get-policies
      description: Get all policy documents, optionally between a given date range.
      summary: /policies
      responses:
        "200":
          description: Policies found.
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: ../models/response/version.yaml
                  - $ref: ../models/response/last_updated.yaml
                  - type: object
                    description: Policies data payload
                    required:
                      - policies
                    properties:
                      policies:
                        type: array
                        items:
                          $ref: ../models/policy.yaml
        "400":
          description: Bad request.
        "404":
          description: Policies not found.
        "406":
          description: MDS version in Accept header is unsupported or invalid.
        "500":
          description: Internal server error.
          content:
            text/plain:
              schema:
                type: string

  /policies/{policy_id}:
    parameters:
      - name: policy_id
        schema:
          $ref: ../models/data-types/uuid.yaml
        in: path
        required: true
        description: The `policy_id` of a Policy document.
    get:
      operationId: get-policies-policy_id
      description: Get the specified policy document.
      summary: /policies/{policy_id}
      responses:
        "200":
          description: Policy document found.
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: ../models/response/version.yaml
                  - $ref: ../models/response/last_updated.yaml
                  - type: object
                    description: Policies data payload
                    required:
                      - policies
                    properties:
                      policies:
                        type: array
                        maxItems: 1
                        minItems: 1
                        items:
                          $ref: ../models/policy.yaml
        "400":
          description: Bad request.
        "404":
          description: Policy not found.
        "406":
          description: MDS version in Accept header is unsupported or invalid.
        "500":
          description: Internal server error.
          content:
            text/plain:
              schema:
                type: string

  /policies.json:
    get:
      operationId: get-policies.json
      description: Get all policy documents in a single JSON file.
      summary: /policies.json
      responses:
        "200":
          description: Policies found.
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: ../models/response/version.yaml
                  - $ref: ../models/response/last_updated.yaml
                  - type: object
                    description: Policies data payload
                    required:
                      - policies
                    properties:
                      end_date:
                        $ref: ../models/data-types/timestamp.yaml
                        description: Optional timestamp that applies to the file as a whole.
                      policies:
                        type: array
                        items:
                          $ref: ../models/policy.yaml
        "404":
          description: Policies not found.
        "406":
          description: MDS version in Accept header is unsupported or invalid.
        "500":
          description: Internal server error.
          content:
            text/plain:
              schema:
                type: string

  /value:
    get:
      operationId: get-value
      description: |-
        An Agency may wish to provide dynamic or global rules, e.g.

        > "Within 300 yards of the stadium, 1000 total extra scooters may be deployed, across all Provider(s)."

        In this case, compliance is not computable from the information available to a single Provider. The Agency may provide
        an endpoint to get the current count of vehicles in the service-area, so that individual Providers could decide whether
        adding some number to those present is allowed.
      summary: /value
      responses:
        "200":
          description: Value found.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required:
                  - value
                  - timestamp
                  - policy_id
                properties:
                  value:
                    type: integer
                    description: Value of whatever the rule measures.
                  timestamp:
                    $ref: ../models/data-types/timestamp.yaml
                    description: Timestamp the value was recorded.
                  policy_id:
                    $ref: ../models/data-types/uuid.yaml
                    description: Relevant `policy_id` for reference.

  /requirements:
    get:
      operationId: get-requirements
      description: |-
        Enumerates all of the parts of MDS, CDS, GBFS, and other specifications that an agency requires from
        providers for certain programs, including APIs, endpoints, and optional fields, as well as information for providers
        about the APIs the agency is hosting.
      summary: /requirements
      responses:
        "200":
          description: Requirements found.
          content:
            application/json:
              schema:
                type: object
                description: Requirements data payload
                required:
                  - requirements
                properties:
                  requirements:
                    $ref: ../models/requirements.yaml
        "404":
          description: Requirements not found.
        "406":
          description: MDS version in Accept header is unsupported or invalid.
        "500":
          description: Internal server error.
          content:
            text/plain:
              schema:
                type: string
