name: Lint OpenAPI documents

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: npm ci

      - name: lint models
        run: npx spectral lint ./reference/**/*.yaml --ruleset .spectral.models.yaml --fail-severity warn

      - name: lint OpenAPI docs
        run: npx spectral lint ./reference/**/*.yaml --ruleset .spectral.yaml
